Features:
    aa_000: float64
    ab_000: float64
    ac_000: float64
    ad_000: float64
    ae_000: float64
    af_000: float64
    ag_000: float64
    ag_001: float64
    ag_002: float64
    ag_003: float64
    ag_004: float64
    ag_005: float64
    ag_006: float64
    ag_007: float64
    ag_008: float64
    ag_009: float64
    ah_000: float64
    ai_000: float64
    aj_000: float64
    ak_000: float64
    al_000: float64
    am_0: float64
    an_000: float64
    ao_000: float64
    ap_000: float64
    aq_000: float64
    ar_000: float64
    as_000: float64
    at_000: float64
    au_000: float64
    av_000: float64
    ax_000: float64
    ay_000: float64
    ay_001: float64
    ay_002: float64
    ay_003: float64
    ay_004: float64
    ay_005: float64
    ay_006: float64
    ay_007: float64
    ay_008: float64
    ay_009: float64
    az_000: float64
    az_001: float64
    az_002: float64
    az_003: float64
    az_004: float64
    az_005: float64
    az_006: float64
    az_007: float64
    az_008: float64
    az_009: float64
    ba_000: float64
    ba_001: float64
    ba_002: float64
    ba_003: float64
    ba_004: float64
    ba_005: float64
    ba_006: float64
    ba_007: float64
    ba_008: float64
    ba_009: float64
    bb_000: float64
    bc_000: float64
    bd_000: float64
    be_000: float64
    bf_000: float64
    bg_000: float64
    bh_000: float64
    bi_000: float64
    bj_000: float64
    bk_000: float64
    bl_000: float64
    bm_000: float64
    bn_000: float64
    bo_000: float64
    bp_000: float64
    bq_000: float64
    br_000: float64
    bs_000: float64
    bt_000: float64
    bu_000: float64
    bv_000: float64
    bx_000: float64
    by_000: float64
    bz_000: float64
    ca_000: float64
    cb_000: float64
    cc_000: float64
    cd_000: float64
    ce_000: float64
    cf_000: float64
    cg_000: float64
    ch_000: float64
    ci_000: float64
    cj_000: float64
    ck_000: float64
    cl_000: float64
    cm_000: float64
    cn_000: float64
    cn_001: float64
    cn_002: float64
    cn_003: float64
    cn_004: float64
    cn_005: float64
    cn_006: float64
    cn_007: float64
    cn_008: float64
    cn_009: float64
    co_000: float64
    cp_000: float64
    cq_000: float64
    cr_000: float64
    cs_000: float64
    cs_001: float64
    cs_002: float64
    cs_003: float64
    cs_004: float64
    cs_005: float64
    cs_006: float64
    cs_007: float64
    cs_008: float64
    cs_009: float64
    ct_000: float64
    cu_000: float64
    cv_000: float64
    cx_000: float64
    cy_000: float64
    cz_000: float64
    da_000: float64
    db_000: float64
    dc_000: float64
    dd_000: float64
    de_000: float64
    df_000: float64
    dg_000: float64
    dh_000: float64
    di_000: float64
    dj_000: float64
    dk_000: float64
    dl_000: float64
    dm_000: float64
    dn_000: float64
    do_000: float64
    dp_000: float64
    dq_000: float64
    dr_000: float64
    ds_000: float64
    dt_000: float64
    du_000: float64
    dv_000: float64
    dx_000: float64
    dy_000: float64
    dz_000: float64
    ea_000: float64
    eb_000: float64
    ec_00: float64
    ed_000: float64
    ee_000: float64
    ee_001: float64
    ee_002: float64
    ee_003: float64
    ee_004: float64
    ee_005: float64
    ee_006: float64
    ee_007: float64
    ee_008: float64
    ee_009: float64
    ef_000: float64
    eg_000: float64
Target:
    class: int64
columns_with_more_than_50%_missing_values:
    ab_000: float64
    bm_000: float64
    bn_000: float64
    bo_000: float64
    bp_000: float64
    bq_000: float64
    br_000: float64
    cr_000: float64
columns_with_zero_standard_deviation:
    cd_000: float64
histogram_columns:
    ag_000: float64
    ag_001: float64
    ag_002: float64
    ag_003: float64
    ag_004: float64
    ag_005: float64
    ag_006: float64
    ag_007: float64
    ag_008: float64
    ag_009: float64
    ay_000: float64
    ay_001: float64
    ay_002: float64
    ay_003: float64
    ay_004: float64
    ay_005: float64
    ay_006: float64
    ay_007: float64
    ay_008: float64
    ay_009: float64
    az_000: float64
    az_001: float64
    az_002: float64
    az_003: float64
    az_004: float64
    az_005: float64
    az_006: float64
    az_007: float64
    az_008: float64
    az_009: float64
    ba_000: float64
    ba_001: float64
    ba_002: float64
    ba_003: float64
    ba_004: float64
    ba_005: float64
    ba_006: float64
    ba_007: float64
    ba_008: float64
    ba_009: float64
    cn_000: float64
    cn_001: float64
    cn_002: float64
    cn_003: float64
    cn_004: float64
    cn_005: float64
    cn_006: float64
    cn_007: float64
    cn_008: float64
    cn_009: float64
    cs_000: float64
    cs_001: float64
    cs_002: float64
    cs_003: float64
    cs_004: float64
    cs_005: float64
    cs_006: float64
    cs_007: float64
    cs_008: float64
    cs_009: float64
    ee_000: float64
    ee_001: float64
    ee_002: float64
    ee_003: float64
    ee_004: float64
    ee_005: float64
    ee_006: float64
    ee_007: float64
    ee_008: float64
    ee_009: float64
